--[[
  Game Boy: Multi-Export v1.3
  Michael R. Cook
 
  This script will export an image to GBDK or RGBDS compatible formats.
 
  *********************************************************
  ** IMPORTANT: use an indexed palette of only 4 colours **
  *********************************************************
]]

-- use your own default configuration here:
local defaultConfig < const > = {
  mode = "By Slices",
  tileSize = "8x8", direction = "Horizontal", sortBy = "Name",
  format = "GBDK", asmLabels = true, dedupe = true, onlyCurrent = true
}

-- Image must use an indexed palette
if not app.activeSprite or app.activeSprite.colorMode ~= ColorMode.INDEXED then
  app.alert("Requires an Indexed Sprite.") return
end

function processData(args, sprite)
  local isGBDK = (args.format == "GBDK")
  local comment = isGBDK and "//" or ";"

  -- Determine tile dimensions
  local tW, tH = 8, 8
  if args.tileSize == "8x16" then tH = 16
  elseif args.tileSize == "16x16" then tW, tH = 16, 16
  elseif args.tileSize == "32x32" then tW, tH = 32, 32
  end

  -- Validate sprite alignment
  if (sprite.width % tW ~= 0 or sprite.height % tH ~= 0) and args.mode ~= "By Slices" then
    return app.alert(string.format("Sprite must be multiple of %dx%d.", tW, tH))
  end

  -- main conversion logic
  local uniqueTiles, tilesList, maps = {}, {}, {}
  local nextID = 0
  local frameList = args.onlyCurrent and {app.activeFrame} or sprite.frames

  local img = Image(sprite.spec)
  local step = 0 -- set with region discovery

  for _, frame in ipairs(frameList) do
    local frameMap = {}
    img:clear()
    img:drawSprite(sprite, frame)

    local regions = {}

    -- collect the sprites based on their mode/format
    if args.mode == "By Slices" then
      if #sprite.slices == 0 then app.alert("No slices found!") return end

      local sortedSlices = {}
      for _, s in ipairs(sprite.slices) do
        table.insert(sortedSlices, s)
      end

      table.sort(sortedSlices, function(a, b)
        if args.sortBy == "Name" then
          return string.lower(a.name) < string.lower(b.name)
        end
        return a.bounds.y < b.bounds.y or (a.bounds.y == b.bounds.y and a.bounds.x < b.bounds.x)
      end)

      for _, s in ipairs(sortedSlices) do
        table.insert(regions, {x = s.bounds.x, y = s.bounds.y, w = s.bounds.width, h = s.bounds.height, name = s.name})
      end
      step = #regions
    else
      local w, h = sprite.width, sprite.height
      if args.direction == "Horizontal" then
        for y = 0, h - 1, tH do
          for x = 0, w - 1, tW do
            table.insert(regions, {x = x, y = y, w = tW, h = tH, name = string.format("%d,%d", x, y)})
          end
        end
        step = w / tW
      else
        for x = 0, w - 1, tW do
          for y = 0, h - 1, tH do
            table.insert(regions, {x = x, y = y, w = tW, h = tH, name = string.format("%d,%d", x, y)})
          end
        end
        step = h / tH
      end
    end

    -- generate the correct output format + sprite header details
    for i, reg in ipairs(regions) do
      if args.format == "BIN" then
        local tileBytes = getTilesAsRawBytes(img, reg.x, reg.y, reg.w, reg.h)

        -- Simple deduplication check for binary data
        local data = table.concat(tileBytes, ",")
        if not args.dedupe or not uniqueTiles[data] then
          uniqueTiles[data] = true
          for _, b in ipairs(tileBytes) do table.insert(tilesList, b) end
        end
      else
        local data = getTileData(img, reg.x, reg.y, reg.w, reg.h, args.format)
        local label = ""
        if isGBDK then
          if args.mode == "By Slices" then
            label = string.format("  // Name: %s\n", reg.name)
          else
            label = string.format("  // Tile 0x%02X | Pos: %s\n", i, reg.name)
          end
        else
          if args.asmLabels then
            if args.mode == "By Slices" and args.sortBy == "Name" then
              label = string.format("%s::\n", reg.name)
            else
              label = string.format("Sprite%02X::\n", i)
            end
          else
            label = string.format("; Tile 0x%02X | Pos: %s\n", i, reg.name)
          end
        end

        if args.dedupe then
          if not uniqueTiles[data] then
            uniqueTiles[data] = nextID
            table.insert(tilesList, label .. data)
            nextID = nextID + 1
          end
          table.insert(frameMap, uniqueTiles[data])
        else
          table.insert(tilesList, label .. data)
          table.insert(frameMap, nextID)
          nextID = nextID + 1
        end
      end
    end

    table.insert(maps, frameMap)
  end

  local writeMode = "w"
  if args.format == "BIN" then
    writeMode = "wb"
  end
  local f = io.open(args.tileFile, writeMode)

  if args.format == "BIN" then
    f:write(string.pack(string.rep("B", #tilesList), table.unpack(tilesList)))
  else
    -- Write the file header
    f:write(string.format("%s Auto-generated by Game Boy: Multi-Export v1.3\n%s", comment, comment))
    f:write("\n")
    f:write(string.format("%s Input: %s\n", comment, app.fs.fileName(app.activeSprite.filename)))
    f:write(string.format("%s Export: %s | ", comment, args.format))
    if args.mode == "By Slices" then
      f:write(string.format("By Slices | Sort By %s", args.sortBy))
    else
      f:write(string.format("%s Tiles | %s", args.tileSize, args.direction))
    end
    if args.dedupe then
      f:write(" | de-duped")
    end
    f:write("\n\n")

    -- Write all tiles to the file
    if isGBDK then
      local arrayName = app.fs.fileTitle(args.tileFile):gsub("[%s%-]", "_")
      f:write(string.format("const unsigned char %s[] = {\n", arrayName))
      f:write(table.concat(tilesList, "\n\n"))
      f:write("\n};\n")
    else
      if args.asmLabels then f:write("Tiles::\n\n") end
      f:write(table.concat(tilesList, "\n\n"))
      if args.asmLabels then f:write("\n\nTilesEnd::") end
    end
  end

  f:close()

  app.alert("Export Complete!")
end

-- Convert image pixel data to Game Boy 2BPP as raw bytes.
function getTilesAsRawBytes(img, x, y, w, h)
  local tiles = {}
  for tx = 0, w - 1, 8 do
    for ty = 0, h - 1, 8 do
      for cy = 0, 7 do
        local lo, hi = 0, 0
        for cx = 0, 7 do
          local px = img:getPixel(x + tx + cx, y + ty + cy) & 3
          if (px & 1) ~= 0 then lo = lo | (1 << (7 - cx)) end
          if (px & 2) ~= 0 then hi = hi | (1 << (7 - cx)) end
        end
        table.insert(tiles, lo)
        table.insert(tiles, hi)
      end
    end
  end
  return tiles
end

-- Convert image pixel data to Game Boy 2BPP as code.
function getTileData(img, x, y, w, h, format)
  local isASM = false
  if format == "RGBDS HEX (DB)" then
    isASM = true
  end

  local tiles = {}
  for tx = 0, w - 1, 8 do
    for ty = 0, h - 1, 8 do
      if format == "RGBDS" then
        table.insert(tiles, getRGBDS8x8(img, x + tx, y + ty))
      else
        table.insert(tiles, getHex8x8(img, x + tx, y + ty, isASM))
      end
    end
  end
  return table.concat(tiles, "\n")
end

-- Generates 8x8 tile in either Assembly or C hexadecimal format.
function getHex8x8(img, x, y, isASM)
  local bytes = {}
  for cy = 0, 7 do
    local lo, hi = 0, 0
    for cx = 0, 7 do
      local px = img:getPixel(x + cx, y + cy) & 3
      if (px & 1) ~= 0 then lo = lo | (1 << (7 - cx)) end
      if (px & 2) ~= 0 then hi = hi | (1 << (7 - cx)) end
    end
    table.insert(bytes, string.format("0x%02X", lo))
    table.insert(bytes, string.format("0x%02X", hi))
  end

  if isASM then
    return "DB " .. table.concat(bytes, ", ")
  end
  return "  " .. table.concat(bytes, ", ") .. ","
end

-- Generates an RGBDS string for a single 8x8 tile
function getRGBDS8x8(img, x, y)
  local rows = {}
  for cy = 0, 7 do
    local row = {}
    for cx = 0, 7 do
      table.insert(row, img:getPixel(x + cx, y + cy) & 3)
    end
    table.insert(rows, "DW `" .. table.concat(row))
  end
  return table.concat(rows, "\n") .. "\n"
end

function showExportDialogue(prevCfg)
  local dlg = Dialog{title = "Game Boy: Multi-Export v1.3", autofit = true}

  local sprite = app.activeSprite
  -- If no previous config is present, set some defaults
  local cfg = prevCfg or defaultConfig

  local isBIN = (cfg.format == "BIN")
  local isGBDK = (cfg.format == "GBDK")

  -- Set default filename using the same directory as the .ase file
  local fileExt = ""
  if isBIN then
    fileExt = "bin"
  elseif isGBDK then
    fileExt = "c"
  else
    fileExt = "inc"
  end

  local filename = app.fs.fileTitle(sprite.filename) .. "-tiles." .. fileExt
  dlg:file{
    id = "tileFile",
    label = "Output File",
    save = true,
    filename = app.fs.joinPath(app.fs.filePath(sprite.filename), filename),
    filetypes = {"bin", "c", "inc"},
  }
  dlg:separator()

  dlg:combobox{
    id = "mode", label = "Export Mode:", option = cfg.mode, options = {"Full Canvas (Grid)", "By Slices"},
    onchange = function()
      -- close and re-open dialogue using current config
      local currentCfg = dlg.data
      currentCfg.bounds = dlg.bounds
      dlg:close()
      showExportDialogue(currentCfg)
    end
  }

  -- Toggle options visibility based on the export mode
  local isSlices = (cfg.mode == "By Slices")
  -- Full canvas mode:
  dlg:combobox{id = "tileSize", label = "Tile Size:", option = cfg.tileSize, options = {"8x8", "8x16", "16x16", "32x32"}, visible = not isSlices}
  dlg:combobox{id = "direction", label = "Parse Direction:", option = cfg.direction, options = {"Horizontal", "Vertical"}, visible = not isSlices}
  -- Slices mode:
  dlg:combobox{id = "sortBy", label = "Sort Slices:", option = cfg.sortBy, options = {"Position", "Name"}, visible = isSlices}
  dlg:separator()

  dlg:combobox{
    id = "format", label = "Output Format:", option = cfg.format, options = {"BIN", "GBDK", "RGBDS", "RGBDS HEX (DB)"},
    onchange = function()
      if isGBDK or isBIN then
        dlg.data.asmLabels = false
      else
        dlg.data.asmLabels = defaultConfig.asmLabels
      end
      dlg:modify{
        id = "asmLabels",
        selected = cfg.asmLabels,
        enabled = (not isGBDK and not isBIN),
        visible = (not isGBDK and not isBIN),
      }

      local currentCfg = dlg.data
      currentCfg.bounds = dlg.bounds
      dlg:close()
      showExportDialogue(currentCfg)
    end
  }

  -- is not available when GBDK output format
  dlg:check{
    id = "asmLabels",
    label = "Add ASM labels",
    selected = (cfg.asmLabels and cfg.format ~= "GBDK"),
    enabled = (not isGBDK and not isBIN),
    visible = (not isGBDK and not isBIN),
  }
  dlg:separator()

  dlg:check{id = "dedupe", label = "Remove Duplicates", selected = cfg.dedupe}
  dlg:check{id = "onlyCurrent", label = "Current Frame Only", selected = cfg.onlyCurrent}
  dlg:button{id = "ok", text = "Export", focus = true}
  dlg:button{id = "cancel", text = "Cancel"}

  -- Restore the original position of the dialogue
  if cfg.bounds then
    dlg:show{wait = true, bounds = Rectangle(cfg.bounds.x, cfg.bounds.y, 0, 0)}
  else
    dlg:show()
  end

  if not dlg.data.ok or dlg.data.tileFile == "" then return end

  processData(dlg.data, sprite)
end

showExportDialogue()
